### PR TITLE
Mvp dev

### PR DESCRIPTION
**Pull request by zx100x100**
Add Minimum viable product support.

currently supports 3 copies of Spidey sense, running any number of thermocouples. Outputs the readings over the CAN bus

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
You've got a bunch of trailing whitespace, reviewable shows it nicely if you want to remove it.

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-:-MfAu3rW8mPTVnNLCMcE:baa0ju2)* status: all files reviewed, 8 unresolved discussions (waiting on @dwkletke, @jacobdeery, @JaredWatson, @LanaTomlin, @MattiGen, @QuantumManiac, @Rio6, @wendi-yu, @ZTeper, and @zx100x100)

___
*[main.c, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfArImU1DJkdx7EV7tB:-MfArImU1DJkdx7EV7tC:b-3n49x0) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L1)):*
> ```C
> // TODO(wendi): init external oscillator, then change this to 12MHz
> ```

This has been done?
___
*[main.c, line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfArXVh8jBVLf7LDvsg:-MfArXVh8jBVLf7LDvsh:b-qf9k72) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L40)):*
> ```
>     //now that the clock is setup
>     //give the temp chip time to boot
> ```
Nit, spaces after comment slashes.
___
*[main.c, line 88 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAs6KH8aXMod4-EABL:-MfAs6KH8aXMod4-EABM:b8h10ms) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L88)):*
> ```C
>     
>     uint32_t last_millis = millis();
>     uint32_t last_measure_millis = millis();
> ```

`last_measure_millis` is obsolete.
___
*[main.c, line 138 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAsOqJ2pDNdS4OjtLo:-MfAsOqJ2pDNdS4OjtLp:byp18fd) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L138)):*
> ```C
>             send_status_ok();
>             
>             //get_status(cs_write_1);
> ```

Remove
___
*[spi.h, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAsfwa3e-XzhG0wzZP:-MfAsfwa3e-XzhG0wzZQ:byp18fd) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/spi.h#L8)):*
> ```objc
> #include <stdbool.h>
> 
> uint8_t test_data[7];
> ```

Remove
___
*[spi.c, line 66 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAszoM0oj25kPtYw-y:-MfAszoM0oj25kPtYw-z:bp1rw2) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/spi.c#L66)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         while (!SPI1STATUSbits.TXBE);
>         SPI1TXB = send_data[idx];
>         while (!PIR2bits.SPI1RXIF);
>         PIR2bits.SPI1RXIF = 0;
>         receive_data[idx] = SPI1RXB;
> ```
</details>

This could use some comments
___
*[spi.c, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAtBlG6xZXnX1dH2yn:-MfAtBlG6xZXnX1dH2yo:b-ii6b37) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/spi.c#L68)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         /*do {
>             SPI1RXRE = 0;
>             receive_data[idx] = SPI1RXB;
>             test_byte = receive_data[idx];
>         } while (SPI1STATUSbits.RXRE);*/
> ```
</details>

Remove
___
*[temperature.c, line 112 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAtjD-26-z0eM5VN7J:-MfAtjD00mv9w-YSIGtq:b-idrei2) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/temperature.c#L112)):*
> ```
>         //result = 0x00100000; // return -8191 and 1023/1024 degrees
>         result = 0x55555555;
> ```
Undo values from testing

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1)* status: all files reviewed, 13 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @jacobdeery, @JaredWatson, @LanaTomlin, @MattiGen, @QuantumManiac, @Rio6, @ZTeper, and @zx100x100)

___
*[main.c, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfArImU1DJkdx7EV7tB:-Mfo3EUW312ag0IxeF_N:b-9pirqr) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L1)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This has been done?
</blockquote></details>

I think  Zach just forgot to remove when copying, I've never touched this repo lol
___
*[main.c, line 38 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo3X1F9ER74SGFC3zj:-Mfo3X1G0m7ykbXD1h46:bkv53vx) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L38)):*
> ```C
>     osc_init();
>     spi_init();
>     
> ```

Some extra whitespaces here (and in a few other places)
___
*[main.c, line 76 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo3lvIADvSTNgCIN5z:-Mfo3lvIADvSTNgCIN6-:b6ng7ix) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L76)):*
> ```C
>         config_tc(board_2_map[idx], cs_write_2);
>     }
>     for(uint8_t idx = 0; idx < strlen(board_2_map); idx++){
> ```

should this be `board_3_map`?
___
*[main.c, line 155 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo4HI-6rlH-rCIhW3K:-Mfo4HI-6rlH-rCIhW3L:b-g664kb) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L155)):*
> ```C
> 
>         case MSG_RESET_CMD:
>             RESET();
> ```

need a `break;` after this?
___
*[setup.c, line 57 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo4UDCBob2dZ7-ybp-:-Mfo4UDCBob2dZ7-ybp0:bl3xath) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/setup.c#L57)):*
> ```C
>         RESET();
>     }
> }
> ```

final newline
___
*[spi.c, line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo4YRQ8IhdalHQXD5r:-Mfo4YRQ8IhdalHQXD5s:bgbhly9) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/spi.c#L7)):*
> ```C
> void spi_init(void){
>     
>     //Configure Periferal Pin Select registers
> ```

Peripheral

**Review by QuantumManiac — DISMISSED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1)* status: all files reviewed, 14 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @jacobdeery, @JaredWatson, @LanaTomlin, @MattiGen, @Rio6, @ZTeper, and @zx100x100)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MkxoURBAv37NeYcQ86F:-MkxoURBAv37NeYcQ86G:b-2pkpny) (no related file):*
Couldn't find anything new myself. Should be fine to address the comments above for now.

---

**Review by zx100x100 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1)* status: all files reviewed, 11 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @jacobdeery, @JaredWatson, @LanaTomlin, @MattiGen, @Rio6, @wendi-yu, @ZTeper, and @zx100x100)

___
*[main.c, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfArImU1DJkdx7EV7tB:-Ms8DiLO5RzVZqjdUBTn:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L1)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think  Zach just forgot to remove when copying, I've never touched this repo lol
</blockquote></details>

done
___
*[main.c, line 38 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo3X1F9ER74SGFC3zj:-Ms8DjpL2wSNEHVuAZAM:bx0mheo) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L38)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Some extra whitespaces here (and in a few other places)
</blockquote></details>

saving in VS code seems to kill them, done
___
*[main.c, line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfArXVh8jBVLf7LDvsg:-Ms8Dote1UuhhT_G-wp8:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L40)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

> ```
>     //now that the clock is setup
>     //give the temp chip time to boot
> ```
Nit, spaces after comment slashes.
</blockquote></details>

done
___
*[main.c, line 76 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo3lvIADvSTNgCIN5z:-Ms8EkgqD9-c8TrShydy:b-it8mg6) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L76)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

should this be `board_3_map`?
</blockquote></details>

yeah, nice catch, done
___
*[main.c, line 88 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAs6KH8aXMod4-EABL:-Ms8Gbno2DB5Ahc5GLpA:b-7ql1td) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L88)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`last_measure_millis` is obsolete.
</blockquote></details>

fixed
___
*[main.c, line 138 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAsOqJ2pDNdS4OjtLo:-Ms8GggP25Kq8mVGfE4r:b-7rl0kd) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L138)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

done
___
*[main.c, line 155 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo4HI-6rlH-rCIhW3K:-Ms8Gi9JAGfO5DVcXeYH:bgi552c) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L155)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

need a `break;` after this?
</blockquote></details>

nope, since RESET starts the whole code over again
___
*[setup.c, line 57 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo4UDCBob2dZ7-ybp-:-Ms8GqrR5oIbjhaIL4lo:b9luzps) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/setup.c#L57)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

final newline
</blockquote></details>

thx, killed
___
*[spi.h, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAsfwa3e-XzhG0wzZP:-Ms8Gtmn8UYa5bDN0jF-:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/spi.h#L8)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

done
___
*[spi.c, line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo4YRQ8IhdalHQXD5r:-Ms8GuhD8gB7BJWetr0v:b2nid0f) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/spi.c#L7)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Peripheral
</blockquote></details>

thx
___
*[spi.c, line 66 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAszoM0oj25kPtYw-y:-Ms8Iyq04_j0WHLu-cEX:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/spi.c#L66)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

> ```
>         while (!SPI1STATUSbits.TXBE);
>         SPI1TXB = send_data[idx];
>         while (!PIR2bits.SPI1RXIF);
>         PIR2bits.SPI1RXIF = 0;
>         receive_data[idx] = SPI1RXB;
> ```
This could use some comments
</blockquote></details>

done
___
*[spi.c, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAtBlG6xZXnX1dH2yn:-Ms8J-9g0iCSCb70H6NN:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/spi.c#L68)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

> ```
>         /*do {
>             SPI1RXRE = 0;
>             receive_data[idx] = SPI1RXB;
>             test_byte = receive_data[idx];
>         } while (SPI1STATUSbits.RXRE);*/
> ```
Remove
</blockquote></details>

done
___
*[temperature.c, line 112 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAtjD-26-z0eM5VN7J:-Ms8J1-b9sZuyy1CM1vy:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/temperature.c#L112)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

> ```
>         //result = 0x00100000; // return -8191 and 1023/1024 degrees
>         result = 0x55555555;
> ```
Undo values from testing
</blockquote></details>

done

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1)* status: all files reviewed, 6 unresolved discussions (waiting on @dwkletke, @JaredWatson, @LanaTomlin, @MattiGen, @QuantumManiac, @Rio6, @wendi-yu, @ZTeper, and @zx100x100)

___
*[main.c, line 88 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MfAs6KH8aXMod4-EABL:-MsBJxNJ5TAO30pHbt81:b4p100z) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/main.c#L88)):*
<details><summary><i>Previously, zx100x100 (Zachariah Mears) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

I think it's now unused, best to remove it.
___
*[setup.c, line 57 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-Mfo4UDCBob2dZ7-ybp-:-MsBKLGN2OJQGUSkx5yP:bem6x4i) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/ee53ca7208d9b255d6cbe4c7e84c4f77b4f0847d/setup.c#L57)):*
<details><summary><i>Previously, zx100x100 (Zachariah Mears) wrote…</i></summary><blockquote>

thx, killed
</blockquote></details>

Good practice is to have a final newline lol
___
*[spi.h, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-MsBKRG8-fnJSAd6SsHX:-MsBKRG8-fnJSAd6SsHY:b-3b59og) ([raw file](https://github.com/waterloo-rocketry/cansw_temperature_sensing/blob/079eefe4c3a4e1f01b1c0b31276d2cf92591579b/spi.h#L2)):*
> ```objc
> #ifndef SETUP_H
> #define	SETUP_H
> ```

There is a sneaky tab here (and on the endif).

**Review by BluCodeGH — APPROVED** [review]
Alright I'll stop requesting whitespace changes, let's get this in please.

> Dismissed @QuantumManiac from a discussion.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_temperature_sensing/1#-:-N0mvLmQDqQ5Or0s9KF2:b-m8b6ix)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dwkletke, @JaredWatson, @LanaTomlin, @MattiGen, @QuantumManiac, @Rio6, @wendi-yu, and @ZTeper)

**Review by QuantumManiac — APPROVED** [review]

**Pull request merged**
